### PR TITLE
add openapi support

### PR DESCRIPTION
**Pull request by yujunlong2000**
add openapi support

### CODE REVIEW

**Comment by BigstickCarpet** [comment]
Wow!  Awesome!  Thank you **so much** for this!  I haven't had any time to work on this myself, and I know many people will be happy to have this new functionality

**Comment by BigstickCarpet** [comment]
This PR has been released in [version 5.0.0](https://github.com/BigstickCarpet/swagger-parser/blob/master/CHANGELOG.md).  Thank you again for your work!!!

**Comment by thomasdavis** [comment]
@domharrington Sorry for the tag =D But noticed your comment here -> https://readme.readme.io/discuss/5a77a84e7775960026dc21e8

**Comment by domharrington** [comment]
@thomasdavis I've been out for a few days, but expect updates from us soon regarding integrating this. Please follow us on twitter for when it's released: https://twitter.com/readmeio

**Pull request merged**
