### PR TITLE
[v4] Check parameter properties based on type validity

### PR DESCRIPTION
**Pull request by MikeRalphson**
This change checks the following properties against the parameter `type`s they are valid for:

* minimum
* maximum
* exclusiveMinimum
* exclusiveMaximum
* multipleOf
* minLength
* maxLength
* pattern
* minItems
* maxItems
* uniqueItems

### CODE REVIEW

**Comment by BigstickCarpet** [comment]
Thanks for the PR!  I'll take a closer look when I get a chance.  I notice that you're using ES6 `for...of` syntax, which I don't think will work with some of the older browser versions that Swagger Parser supports.  Not 100% sure of that though

**Comment by MikeRalphson** [comment]
No problem, I was expecting to have to rev the PR for style and tests etc.

**Comment by MikeRalphson** [comment]
Reworked to use Array.forEach() as elsewhere in the code.

**Comment by MikeRalphson** [comment]
Hi @BigstickCarpet any feedback?

**Pull request closed without merging**
