### PR TITLE
Add check for duplicate operation ids

### LINKED ISSUE #68: Duplicate operationIds don't cause validation errors
Running `SwaggerParser.validate()` on a Swagger file with `operationId` fields that aren't unique doesn't throw any exception.

The [Swagger specification](http://swagger.io/specification/#operation-object-36) indicates that these fields *must* have unique values:

> Unique string used to identify the operation. **The id MUST be unique among all operations described in the API**. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is recommended to follow common programming naming conventions.

(Emphasis mine)

### PR DESCRIPTION
**Pull request by marcelstoer**
Fixes #68

### CODE REVIEW

**Comment by marcelstoer** [comment]
James, what is your plan with the 4.x branch? Shall I create another PR for this to get back-ported?

**Comment by marcelstoer** [comment]
@BigstickCarpet any feedback yet?

**Comment by BigstickCarpet** [comment]
@marcelstoer - I somehow completely missed this PR, so thank you for pinging me on it.  It looks great!  Thanks for adding a test too 👍

**Comment by BigstickCarpet** [comment]
whoops!  The browser tests failed because `Array.includes()` isn't supported on older browsers.  I'll fix that and retry the tests

**Comment by marcelstoer** [comment]
No worries, how about that question about the 4.x branch above?

**Comment by BigstickCarpet** [comment]
The browser tests (SauceLabs) don't run for PRs because Travis CI doesn't set environment variables (e.g. my SauceLabs credentials) for PR builds.   So browser tests only run once the PR is merged into Master.  

As for the 4.x branch... It's no longer actively supported/maintained.  It's mostly just there for archival purposes, and maybe hotfixes.  Is there a particular reason you're using 4.x instead of 5.x?

**Comment by marcelstoer** [comment]
>  Is there a particular reason you're using 4.x instead of 5.x?

I'm not, was just asking out of curiosity. Every project has a different policy.

**Comment by BigstickCarpet** [comment]
ah, ok.  Well let's just leave this on 5.x then.  I don't think anybody's even using the 4.x branch anymore.

**Comment by argos83** [comment]
This change broke our builds. I wonder if this could have been released as a major version, or if not a minor version, but not a patch. I seems to me that adding validation logic should be considered as adding a feature. Wdyt?

**Comment by marcelstoer** [comment]
I _would_ want this change to break my builds. It means that my Swagger files haven apparently been invalid so far but it went unnoticed. Or did your builds break for different reasons?

**Comment by BenSayers** [comment]
I am part of a large organisation who has thousands of builds that depend on libraries like this. When backward incompatible changes like this are released under a patch version and builds are unexpectedly broken it creates significant disruption. I completely agree we want to know when our Swagger files are invalid, however I don't believe the right way to achieve this is to without warning suddenly force everyone to deal with this, despite what other priorities they have.

**Comment by BigstickCarpet** [comment]
@BenSayers - I apologize for the disruption.  I didn't think this would be a breaking change, since it was just adding a check for something that's already part of the Swagger 2.0 spec.  But you're right, I should have been more careful and released it as a major or minor version bump, not a patch.

For future reference, you can disable the Swagger spec validation in Swagger Parser by setting [the `validate.spec` option](https://github.com/BigstickCarpet/swagger-parser/blob/master/docs/options.md#validate-options) to `false`.  It will still validate your API against the Swagger schema.  It just won't run the additional spec-compliancy checks.

```javascript
var options = {
    validate: {
        spec: false
    },
};

SwaggerParser.validate("my-api.yaml", options, callback);
```

**Pull request merged**
