### PR TITLE
Validate Response Body Schemas

### PR DESCRIPTION
**Pull request by Piefayth**
See #33

### CODE REVIEW

**Comment by marcelstoer** [comment]
I'm so looking forward to this getting eventually merged after more than two years. @Piefayth would you mind rebasing to resolve the conflicts?

**Comment by Piefayth** [comment]
This is updated (I had to include a small change, since the tests changed directories), but there is currently a failing test for an external spec that does not define the top level `swagger` property. Looks like an OAPI 3.0 spec, which makes sense.

**Comment by marcelstoer** [comment]
I'm sorry but _my_ PR that just got merged caused another conflict in your spec file 😦

**Comment by marcelstoer** [comment]
@BigstickCarpet or @Piefayth would one of you be willing to resolve the conflicts so we could finally profit from the goodness this feature brings?

**Comment by BigstickCarpet** [comment]
@marcelstoer  - I'm taking a look at it now

**Pull request merged**
