### PR TITLE
Added support for downloading remote files over https

### LINKED ISSUE #10: Ability to parse a remote file over https

### PR DESCRIPTION
**Pull request by dmyers**
Fixes #10

Could be worth considering the popular [request](https://www.npmjs.com/package/request) module which supports with a simple DSL syntax.

### CODE REVIEW

**Comment by BigstickCarpet** [comment]
Awesome!  Thanks for submitting this.   I'll try to get it merged in and tested later this week.

**Comment by dmyers** [comment]
@BigstickCarpet Thank you! I appreciate it whenever get some time. Right now I download the file and load in the local file, but it could be quicker with this change and I could get rid of the hack. :+1:

**Comment by dmyers** [comment]
@BigstickCarpet Do you think you'll be able to look at this sometime soon? I'd prefer to get rid of my hack if you like it. :)

**Comment by BigstickCarpet** [comment]
Sorry for the delay.  The past two weeks have been *insane* at work (I've been working 16+ hour days), so I haven't had any time to work on this.  But things have calmed down now, so I will be working on this **tonight**, I promise.  :)

**Comment by dmyers** [comment]
Yikes! I know that feeling! No worries. I was working on this for work too. :D

**Comment by BigstickCarpet** [comment]
Done!  Released as v2.4.3

**Comment by dmyers** [comment]
No worries, thanks for creating the project and for your time. :+1:

**Pull request merged**
